#!/usr/bin/env python3
"""Generate an After Effects JSX builder from a footage-linked manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def js_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def js_text_expr(value: str) -> str:
    """Return an AE-safe JS expression for text, avoiding non-ASCII string bugs."""
    if all(32 <= ord(ch) <= 126 and ch not in {'"', "\\"} for ch in value):
        return js_quote(value)
    codes = []
    for ch in value:
        if ch == "\n":
            codes.append("13")
        else:
            codes.append(str(ord(ch)))
    return "S([" + ",".join(codes) + "])"


def color_expr(hex_color: str) -> str:
    s = hex_color.strip().lstrip("#")
    if len(s) == 3:
        s = "".join(ch * 2 for ch in s)
    if len(s) != 6:
        raise ValueError(f"Expected #RRGGBB color, got {hex_color!r}")
    r, g, b = int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)
    return f"C({r},{g},{b})"


def num(value, default=0):
    return default if value is None else value


def layer_js(layer: dict) -> str:
    t = layer["type"]
    name = js_quote(layer.get("name", t))
    opacity = num(layer.get("opacity"), 100)
    if t == "image":
        return (
            f'    addImg(comp, A[{js_quote(layer["file"])}], {name}, '
            f'{num(layer.get("cx"))}, {num(layer.get("cy"))}, '
            f'{num(layer.get("w"))}, {num(layer.get("h"))}, '
            f'{js_quote(layer.get("mode", "contain"))}, {opacity}, '
            f'{num(layer.get("rotation"), 0)});'
        )
    if t == "text":
        return (
            f"    addText(comp, {name}, {js_text_expr(layer.get('text', ''))}, "
            f"{num(layer.get('x'))}, {num(layer.get('y'))}, {num(layer.get('size'), 48)}, "
            f"{color_expr(layer.get('color', '#FFFFFF'))}, "
            f"{str(bool(layer.get('bold'))).lower()}, {opacity}, "
            f"{str(bool(layer.get('center'))).lower()});"
        )
    if t == "solid":
        return (
            f"    addSolid(comp, {name}, {color_expr(layer.get('color', '#000000'))}, "
            f"{num(layer.get('cx'))}, {num(layer.get('cy'))}, "
            f"{num(layer.get('w'))}, {num(layer.get('h'))}, {opacity});"
        )
    raise ValueError(f"Unsupported layer type: {t}")


def generate_jsx(manifest: dict) -> str:
    width = manifest.get("width", 1080)
    height = manifest.get("height", 1920)
    fps = manifest.get("fps", 30)
    duration = manifest.get("duration")
    if duration is None:
        duration = max(scene["start"] + scene["duration"] for scene in manifest["scenes"])

    assets_dir = Path(manifest["assetsDir"]).as_posix()
    reference_mp4 = manifest.get("referenceMp4", "")
    reference_mp4_js = str(reference_mp4).replace("\\", "/")
    output_aep = Path(manifest["outputAep"]).as_posix()
    status_file = Path(
        manifest.get("statusFile", str(Path(output_aep).with_name("AE_BUILD_STATUS.txt")))
    ).as_posix()
    master_comp = manifest.get("masterComp", "AE_FOOTAGE_LINKED_MASTER")

    image_files = sorted(
        {
            layer["file"]
            for scene in manifest["scenes"]
            for layer in scene.get("layers", [])
            if layer.get("type") == "image"
        }
    )

    parts = []
    parts.append(
        f"""/* Generated by make_ae_footage_project.py */
(function () {{
  var W = {width};
  var H = {height};
  var FPS = {fps};
  var DUR = {duration};
  var ASSET = {js_quote(assets_dir)};
  var OUT_AEP = {js_quote(output_aep)};
  var STATUS = {js_quote(status_file)};
  var REF_MP4 = {js_quote(reference_mp4_js)};

  function writeStatus(msg) {{
    var f = new File(STATUS);
    f.open("w");
    f.encoding = "UTF-8";
    f.write(msg);
    f.close();
  }}
  function C(r, g, b) {{ return [r / 255, g / 255, b / 255]; }}
  function S(codes) {{
    var s = "";
    for (var i = 0; i < codes.length; i++) s += String.fromCharCode(codes[i]);
    return s;
  }}
  function mustFile(path) {{
    var f = new File(path);
    if (!f.exists) {{
      writeStatus("MISSING FILE: " + path);
      throw new Error("Missing file: " + path);
    }}
    return f;
  }}
  function importFootage(folder, fileName) {{
    var io = new ImportOptions(mustFile(ASSET + "/" + fileName));
    var item = app.project.importFile(io);
    item.name = fileName;
    item.parentFolder = folder;
    return item;
  }}
  function tr(layer) {{ return layer.property("ADBE Transform Group"); }}
  function setImageLayer(layer, cx, cy, targetW, targetH, mode, opacity, rot) {{
    var sx = targetW / layer.source.width * 100;
    var sy = targetH / layer.source.height * 100;
    var sc = mode == "cover" ? Math.max(sx, sy) : Math.min(sx, sy);
    tr(layer).property("ADBE Scale").setValue([sc, sc]);
    tr(layer).property("ADBE Position").setValue([cx, cy]);
    tr(layer).property("ADBE Opacity").setValue(opacity);
    try {{ tr(layer).property("ADBE Rotate Z").setValue(rot || 0); }} catch (e) {{}}
  }}
  function addImg(comp, item, name, cx, cy, w, h, mode, opacity, rot) {{
    var l = comp.layers.add(item);
    l.name = name;
    setImageLayer(l, cx, cy, w, h, mode || "contain", opacity == null ? 100 : opacity, rot || 0);
    l.inPoint = 0;
    l.outPoint = comp.duration;
    return l;
  }}
  function addSolid(comp, name, color, cx, cy, w, h, opacity) {{
    var l = comp.layers.addSolid(color, name, w, h, 1, comp.duration);
    tr(l).property("ADBE Position").setValue([cx, cy]);
    tr(l).property("ADBE Opacity").setValue(opacity == null ? 100 : opacity);
    return l;
  }}
  function addText(comp, name, text, x, y, size, color, bold, opacity, center) {{
    var l = comp.layers.addText(text);
    l.name = name;
    var doc = l.property("ADBE Text Properties").property("ADBE Text Document").value;
    doc.fontSize = size;
    try {{ doc.font = bold ? "MicrosoftYaHei-Bold" : "MicrosoftYaHei"; }} catch (e) {{}}
    doc.applyFill = true;
    doc.fillColor = color;
    doc.justification = center ? ParagraphJustification.CENTER_JUSTIFY : ParagraphJustification.LEFT_JUSTIFY;
    l.property("ADBE Text Properties").property("ADBE Text Document").setValue(doc);
    tr(l).property("ADBE Position").setValue([x, y]);
    tr(l).property("ADBE Opacity").setValue(opacity == null ? 100 : opacity);
    l.inPoint = 0;
    l.outPoint = comp.duration;
    return l;
  }}

  app.beginSuppressDialogs();
  app.beginUndoGroup("Build footage-linked AE project");
  if (app.project === null) app.newProject();
  writeStatus("RUNNING: building footage-linked AE project");

  var assetFolder = app.project.items.addFolder("01_Linked_Image_Footage");
  var compFolder = app.project.items.addFolder("02_Scene_Precomps");
  var refFolder = app.project.items.addFolder("03_Reference");
  var A = {{}};
"""
    )

    for file_name in image_files:
        parts.append(f"  A[{js_quote(file_name)}] = importFootage(assetFolder, {js_quote(file_name)});\n")

    parts.append(
        f"""
  var master = app.project.items.addComp({js_quote(master_comp)}, W, H, 1, DUR, FPS);
  master.parentFolder = compFolder;
"""
    )

    for scene in manifest["scenes"]:
        comp_name = scene["name"]
        parts.append(
            f"""
  var comp = app.project.items.addComp({js_quote(comp_name)}, W, H, 1, {scene["duration"]}, FPS);
  comp.parentFolder = compFolder;
"""
        )
        for layer in scene.get("layers", []):
            parts.append(layer_js(layer) + "\n")
        parts.append(
            f"""
  var sceneLayer = master.layers.add(comp);
  sceneLayer.name = {js_quote(comp_name)};
  sceneLayer.startTime = {scene["start"]};
  sceneLayer.inPoint = {scene["start"]};
  sceneLayer.outPoint = {scene["start"] + scene["duration"]};
  master.markerProperty.setValueAtTime({scene["start"]}, new MarkerValue({js_quote(comp_name)}));
"""
        )

    parts.append(
        """
  var refFile = new File(REF_MP4);
  if (REF_MP4 !== "" && refFile.exists) {
    var refOpt = new ImportOptions(refFile);
    var refItem = app.project.importFile(refOpt);
    refItem.name = "final_mp4_reference";
    refItem.parentFolder = refFolder;
    var refLayer = master.layers.add(refItem);
    refLayer.name = "MP4 reference - hidden";
    refLayer.enabled = false;
    refLayer.startTime = 0;
    refLayer.outPoint = DUR;
  }

  master.openInViewer();
  app.project.save(new File(OUT_AEP));
  writeStatus("OK: saved " + OUT_AEP);
  app.endUndoGroup();
  app.endSuppressDialogs(false);
})();
"""
    )
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8-sig"))
    jsx = generate_jsx(manifest)
    output = args.output or args.manifest.with_name("build-ae-footage-linked.jsx")
    output.write_text(jsx, encoding="ascii")
    print(output)


if __name__ == "__main__":
    main()
